language: java
install: true

addons:
  sonarcloud:
    organization: "guillaumewaignier-github"
    token:
      secure: "C4/R3l3+2qi9aKNIeFQaNEWT/wI/uKINA8bLCzsMfji+6LpabWmbbw0OVDRcJiyaMyF5Zv2YvNjXRjPZmPdv2eY1y2mvq4q/7c11YOLEGDKmbfwUG0b8MzcqISCpUpOO2Cwk8AS5Egt0PlqpTwI5xT4jd0k3ziEy37EKSLsQUb9ad4awjH7puMsHc2zM4VbpbI5GWGbzQzY8Vo680NQSOwmu0vwFqHim9iSptluPXK79VsvUQ2LeZY/+nxfnqhA1xpeGoWhgcVTo0rrHcjL9nNh2xM09sIWl9aeyYImy/TqiO/0uzZc2izSH36zPccO1/6XDjV0jH6jP+drr/T7wW9Oy0ZgXmld3kYXiqtlO3J6UdXy2DLfHeC11QNVNz47mIApK4qhP4W4xC5eiAxq5rVQ6pgX7lAwWiy1VnC3Oi6DVDXnfHiv/wGAx0WyP6Sq9UBbqPDOn+pZ3PJi8DslutNn0Z27byuHXwYwyKhvKyJSTL6C0gD06QbiU6dvZose1uFrCKdoUFMQEL+qGIK/LSJwGHqBtxvcAQqNyHDA9K54836RVRnNjedoQrd1dnXlSjuusl2hC0potKNSJAIo/27ag7KYL5Zm0jEywX6iT4bBWZFG1HWekD/DgGpaHBTaKDbSiU7ul8hiISk4Bv9Xq8P9ECYt0CPsDQyOEhQieRqs="
jdk:
  - openjdk11


script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'